# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0b490af82028cdce1c80f92aeb0bace30ddb076f4c3e13a6f865d9f812c7474caef40342423aef56956a78def02667deb0d59d22d18ebb99abc9a94088711dd

test:
  secret_key_base: fe13c6368b81a64dc5778bd73c37a462fb776c4c9a0013f14f7fbbe43d11e78579aba40f85da6c23614cea9f1d86d4cc625209e91444f35775369b7b55547988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
